final Map<String, dynamic> testVector = {
  "bigint": BigInt.one,
  "bString": "1",
  "bStringHex": "0756b5b3",
  "wBigInt": "0.1",
  "string": "a",
  "int": 1,
  "intString": "1",
  "double": 1.0,
  "doubleInt": 1,
  "doubleString": "1.0",
  "doubleAsIntString": "1",
  "wDouble": "..123..",
  "bytes": [0, 1],
  "bytesAsHex": "0x00",
  "bytesAsString": "mrtnetwork",
  "wBytes": [257, 0],
  "byteAsBase58": "2cFupjhnEsSn59qHXstmK2ffpLv2",
  "bytesAsBase64": "Mnh0LC54VShsSmdRQ08xVzU=",
  "map": {"one": 1, "two": 2},
  "mapInt": {1: 1, 2: 2},
  "list": ["a", "b"],
  "listDynamic": ["a", 1],
  "listDynamic2": <dynamic>["a", "a"],
  "mapDynamic": <dynamic, dynamic>{"a": "v"},
  "set": {0, 1},
  "setDynamic": <dynamic>{"a", "b"}
};
